import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Principles, ZurichAdvantage } from "@/components/page-sections";

export const Route = createFileRoute("/how-we-work")({
  head: () => ({ meta: [{ title: "How We Work — Novalith Solutions" }, { name: "description", content: "Weekly delivery, senior engineers, architecture-first execution and one accountable project director in Zurich." }, { property: "og:title", content: "How We Work — Novalith Solutions" }, { property: "og:description", content: "Swiss accountability and senior global engineering, from architecture to launch." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/how-we-work" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/how-we-work" }] }), component: Page,
});
function Page() { const steps=[["01","Align","Outcome, scope, risks, and delivery plan."],["02","Architect","Technical foundation and working agreements."],["03","Ship","Weekly product increments with visible progress."],["04","Stabilise","Launch, observe, support, and improve."]]; return <><section className="section pt-36 md:pt-44"><div className="site-container"><p className="eyebrow">Delivery model</p><h1 className="mt-7 max-w-5xl text-5xl font-semibold leading-tight md:text-8xl">Clarity at the start. Momentum every week.</h1></div></section><Principles/><section className="section border-b border-border"><div className="site-container"><p className="eyebrow">The sequence</p><div className="mt-12 grid gap-px border border-border bg-border md:grid-cols-4">{steps.map(([n,t,d])=><div key={n} className="bg-card p-7"><span className="text-xs text-primary">{n}</span><h2 className="mt-12 text-2xl font-semibold">{t}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{d}</p></div>)}</div></div></section><ZurichAdvantage/><section className="section text-center"><h2 className="text-4xl font-semibold md:text-6xl">Ready to move?</h2><Button asChild size="lg" className="mt-8"><Link to="/start-a-project">Start a project <ArrowRight/></Link></Button></section></> }
