/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as StartAProjectRouteImport } from './routes/start-a-project'
import { Route as WhatWeBuildRouteImport } from './routes/what-we-build'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const StartAProjectRoute = StartAProjectRouteImport.update({
  id: '/start-a-project',
  path: '/start-a-project',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeBuildRoute = WhatWeBuildRouteImport.update({
  id: '/what-we-build',
  path: '/what-we-build',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/start-a-project': typeof StartAProjectRoute
  '/what-we-build': typeof WhatWeBuildRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/start-a-project': typeof StartAProjectRoute
  '/what-we-build': typeof WhatWeBuildRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/start-a-project': typeof StartAProjectRoute
  '/what-we-build': typeof WhatWeBuildRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/how-we-work' | '/start-a-project' | '/what-we-build'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/how-we-work' | '/start-a-project' | '/what-we-build'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/how-we-work'
    | '/start-a-project'
    | '/what-we-build'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  StartAProjectRoute: typeof StartAProjectRoute
  WhatWeBuildRoute: typeof WhatWeBuildRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-a-project': {
      id: '/start-a-project'
      path: '/start-a-project'
      fullPath: '/start-a-project'
      preLoaderRoute: typeof StartAProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-build': {
      id: '/what-we-build'
      path: '/what-we-build'
      fullPath: '/what-we-build'
      preLoaderRoute: typeof WhatWeBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  StartAProjectRoute: StartAProjectRoute,
  WhatWeBuildRoute: WhatWeBuildRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
